"""PyInstaller spec generation and distribution assembly."""
from __future__ import annotations

import importlib.util
import json
import os
import sys
from pathlib import Path

from .common import (BASE_EXCLUDES, UPX_EXCLUDES, CLI_NAME, GUI_NAME, BuildOptions,
                     BuildResult, PackageManifest, merge_distribution, run_command,
                     validate_build_directory)


def generate_spec(options: BuildOptions, manifest: PackageManifest) -> str:
    gui_script = str(options.root / f"{GUI_NAME}.py")
    cli_script = str(options.root / f"{CLI_NAME}.py")
    icon_path = str(options.root / "imgs/HNW.jpg")
    binaries = [(str(path), ".") for path in (*manifest.custom_op_dlls, *manifest.turbojpeg_libraries)]
    datas = [(str(path), destination) for path, destination in manifest.data_dirs]
    datas.extend((str(path), str(Path(destination).parent).replace("\\", "/"))
                 for path, destination in manifest.data_files)
    hidden = []
    if manifest.native:
        hidden.append("hoshicore._custom_op._C")
    if manifest.metal_shader:
        hidden.append("hoshicore._custom_op._metal")
    if manifest.turbojpeg:
        hidden.append("turbojpeg")
    excludes = BASE_EXCLUDES + (() if manifest.native else ("hoshicore._custom_op._C",))
    spec = f"""\
# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by make_package.py
from PyInstaller.utils.hooks import collect_all, collect_submodules, copy_metadata

# LOAD-BEARING: pyexiv2 adds its extension directory to sys.path for exiv2api.
import pyexiv2 as _pyexiv2
shared_datas = {datas!r}
shared_binaries = {binaries!r}
shared_hiddenimports = {hidden!r}
_d, _b, _h = collect_all('pyexiv2')
shared_datas += _d + copy_metadata('pyexiv2')
shared_binaries += _b
shared_hiddenimports += _h + collect_submodules('scipy._lib.array_api_compat')
_shared_excludes = {list(excludes)!r}
_native_upx_exclude = {list(UPX_EXCLUDES)!r}

a_gui = Analysis(
    [{gui_script!r}],
    pathex=[{str(options.root)!r}],
    binaries=shared_binaries,
    datas=shared_datas,
    hiddenimports=['PySide6'] + shared_hiddenimports,
    excludes=_shared_excludes,
    noarchive=False,
)

a_cli = Analysis(
    [{cli_script!r}],
    pathex=[{str(options.root)!r}],
    binaries=shared_binaries,
    datas=shared_datas,
    hiddenimports=shared_hiddenimports,
    excludes=['PySide6'] + _shared_excludes,
    noarchive=False,
)

MERGE(
    (a_gui, {GUI_NAME!r}, {GUI_NAME!r}),
    (a_cli, {CLI_NAME!r}, {CLI_NAME!r}),
)

pyz_gui = PYZ(a_gui.pure)
exe_gui = EXE(
    pyz_gui,
    a_gui.scripts,
    [],
    exclude_binaries=True,
    name={GUI_NAME!r},
    debug=False,
    strip=False,
    upx={options.apply_upx!r},
    upx_exclude=_native_upx_exclude,
    console={options.debug_gui!r},
    icon={icon_path!r},
)

pyz_cli = PYZ(a_cli.pure)
exe_cli = EXE(
    pyz_cli,
    a_cli.scripts,
    [],
    exclude_binaries=True,
    name={CLI_NAME!r},
    debug=False,
    strip=False,
    upx={options.apply_upx!r},
    upx_exclude=_native_upx_exclude,
    console=True,
)

coll = COLLECT(
    exe_gui,
    a_gui.binaries,
    a_gui.zipfiles,
    a_gui.datas,
    exe_cli,
    a_cli.binaries,
    a_cli.zipfiles,
    a_cli.datas,
    strip=False,
    upx={options.apply_upx!r},
    upx_exclude=_native_upx_exclude,
    name={options.release_name!r},
)
"""

    if sys.platform == "darwin" and not options.debug_gui:
        spec += f"""\

app = BUNDLE(
    coll,
    name={GUI_NAME + '.app'!r},
    icon={icon_path!r},
    bundle_identifier='com.hoshinoweaver.desktop',
)
"""

    return spec


def describe_release(directory: Path, options: BuildOptions) -> BuildResult:
    suffix = ".exe" if os.name == "nt" else ""
    gui = directory / (GUI_NAME + suffix)
    resources = directory / "_internal"
    gui_resources = resources
    if sys.platform == "darwin" and not options.debug_gui:
        gui = directory / f"{GUI_NAME}.app/Contents/MacOS/{GUI_NAME}"
        gui_resources = gui.parent.parent / "Frameworks"
    return BuildResult(directory, directory / (CLI_NAME + suffix), gui,
                       resources, gui_resources / "logs")


def build(options: BuildOptions, manifest: PackageManifest, stage: Path | None) -> BuildResult:
    if importlib.util.find_spec("PyInstaller") is None:
        raise RuntimeError("PyInstaller is not installed; run python -m pip install -r requirements-dev.txt")
    build_root = validate_build_directory(options.build_dir or options.root / "build/pyinstaller", options)
    metadata_root = options.root / "build/pyinstaller"
    build_root.mkdir(parents=True, exist_ok=True)
    metadata_root.mkdir(parents=True, exist_ok=True)
    spec_path = metadata_root / "HoshiNoWeaver.spec"
    spec_path.write_text(generate_spec(options, manifest), encoding="utf-8")
    output = build_root / "dist"
    command = [sys.executable, "-m", "PyInstaller", "--clean", "--noconfirm",
               "--distpath", str(output), "--workpath", str(build_root / "work"), str(spec_path)]
    (metadata_root / "commands.json").write_text(json.dumps([command], indent=2), encoding="utf-8")
    run_command(command, root=options.root, dry_run=options.dry_run)
    if options.dry_run:
        return describe_release(options.release_dir, options)
    if stage is None:
        raise RuntimeError("Missing release staging directory")
    merge_distribution(output / options.release_name, stage)
    if sys.platform == "darwin" and not options.debug_gui:
        app = output / f"{GUI_NAME}.app"
        merge_distribution(app, stage / app.name)
    return describe_release(stage, options)


def postprocess(result: BuildResult, options: BuildOptions) -> None:
    # UPX is applied by EXE/COLLECT with the shared exclusions.
    pass
